"""movie status

Revision ID: 1a9bda541123
Revises: 7ebfd2af8d78
Create Date: 2025-11-30 21:32:27.992395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a9bda541123'
down_revision = '7ebfd2af8d78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fridge_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fridge_item_name'))
        batch_op.create_unique_constraint('uq_fridge_item_name_category', ['name', 'category'])

    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=64), nullable=False))
        batch_op.drop_index(batch_op.f('ix_movie_name'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movie_name'), ['name'], unique=False)
        batch_op.drop_column('status')

    with op.batch_alter_table('fridge_item', schema=None) as batch_op:
        batch_op.drop_constraint('uq_fridge_item_name_category', type_='unique')
        batch_op.create_index(batch_op.f('ix_fridge_item_name'), ['name'], unique=False)

    # ### end Alembic commands ###
